CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE store_category
(
    category_id BIGINT NOT NULL,
    store_id    BIGINT NOT NULL,
    CONSTRAINT pk_store_category PRIMARY KEY (category_id, store_id)
);

ALTER TABLE store_category
    ADD CONSTRAINT fk_stocat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE store_category
    ADD CONSTRAINT fk_stocat_on_store FOREIGN KEY (store_id) REFERENCES store (id);