name: Docker Image CI

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    branches: [ "release/**" ]

env:
  DOCKER_IMAGE_NAME: project24
  DOCKER_REGISTRY_URL: beepbip/project24

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version
        # i.e.: release/1.0.0 -> 1.0.
        id: strip-branch-name
        run: |
          release_version=$(echo "${{ github.ref }}" | sed 's/refs\/heads\/.*\///')
          echo "Building release version $release_version"
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          shell: bash

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION

      - name: Tag the image for the private registry $DOCKER_REGISTRY_URL
        run: docker tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

      - name: Create a latest image as well
        run: docker tag $DOCKER_IMAGE_NAME:$RELEASE_VERSION $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

      - name: Push the Docker image with version number
        run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

      - name: Push the latest tag
        run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

      - name: Remove the Docker image with version number
        run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$RELEASE_VERSION

      - name: Remove the Docker image with latest tag
        run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

      - name: Remove the local image
        run: docker rmi $DOCKER_IMAGE_NAME:$RELEASE_VERSION
